services:
  db-init:
    image: alpine:latest
    container_name: db-init
    volumes:
      - autosupport-db:/var/lib/sqlite
    entrypoint: >
      sh -c "if [ ! -f /var/lib/sqlite/autosupport.db ]; then
        apk add --no-cache sqlite &&
        echo 'Creating SQLite database at /var/lib/sqlite/autosupport.db' &&
        sqlite3 /var/lib/sqlite/autosupport.db 'VACUUM;';
      fi &&
      chown -R 1000:1000 /var/lib/sqlite"

  autosupport:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
      target: release
    container_name: autosupport
    environment:
      - OP_UNBOUND_TOKEN
    volumes:
      - autosupport-db:/var/lib/sqlite
    entrypoint: sh -c "ln -sf /var/lib/sqlite/autosupport.db /usr/src/app/autosupport.db && bun start"
    depends_on:
      db-init:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD-SHELL", "find /usr/src/app/healthcheck.tmp -mmin -2 | grep -q ."]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s

volumes:
  autosupport-db:
