[support]

[[support."709061970078335027"]]
problem = "I asked a question but didn't get a helpful answer."
solution = "The information you provided may not be detailed enough. Please try to include more context or rephrase your question so it can be better understood."

[[support."709061970078335027"]]
problem = "How do I enable the mobile account switcher?"
solution = "First, enable Discord Experiments. Then locate the 'Mobile Account Switcher' experiment and set it to Treatment 1. You can hold your profile icon in the navigation tab to manage accounts."

[[support."709061970078335027"]]
problem = "Notifications aren't working on my iOS device."
solution = "For jailed devices, make sure the `.ipa` is signed with a certificate that includes the notification (apn) entitlement. Note: this channel does not provide sideloading support."
notes = "Additionally to the entitlement, the app must also match the bundle ID of the official app. This will increase the risk of Apple revoking the certificate and disabling the ADP account it belongs to."

[[support."709061970078335027"]]
problem = "Can I use AltStore PAL to sideload apps?"
solution = "No, AltStore PAL is for notarized apps only and cannot be used to sideload. For sideloading, use other methods. Note: this channel does not provide sideloading support."
notes = "AltStore itself is a sideloading tool but AltStore PAL is an App Marketplace for notarized apps."
